// <auto-generated />
namespace ProjetoVinhos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class criaBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criaBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201901290027503_criaBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
